#include "limine_manager/render/limine_renderer.hpp"

#include <sstream>
#include <stdexcept>

namespace limine_manager::render {
namespace {
void render_node(std::ostringstream& out, const domain::MenuNode& node, std::size_t depth) {
    if (depth == 0) throw std::logic_error("Menu depth starts at one");
    out << std::string(depth, '/') << (node.expanded ? "+" : "") << node.title << '\n';
    if (node.comment && !node.comment->empty()) out << "    comment: " << *node.comment << '\n';
    if (node.kind == domain::NodeKind::linux_entry) {
        if (!node.boot) throw std::logic_error("Linux entry has no boot specification");
        out << "    protocol: linux\n";
        out << "    path: " << node.boot->kernel_path << '\n';
        for (const auto& module : node.boot->module_paths) out << "    module_path: " << module << '\n';
        out << "    cmdline: " << node.boot->cmdline << '\n';
    }
    for (const auto& child : node.children) render_node(out, child, depth + 1);
    out << '\n';
}
}

std::string LimineRenderer::render(const domain::MenuDocument& document) const {
    std::ostringstream out;
    out << "# Generated by limine-manager. Do not edit manually.\n";
    for (const auto& [name, value] : document.global_options) out << name << ": " << value << '\n';
    out << '\n';
    for (const auto& root : document.roots) render_node(out, root, 1);
    return out.str();
}

} // namespace limine_manager::render
